disciplines = {'Aerospace'; 'Applied Physics'; ...
    'Biomedical'; 'Chemical'; 'Civil and Environmental'; ...
    'Climate and Space Sciences'; 'Electrical'; ...
    'Computer Science'; 'Industrial and Operations'; ...
    'Integrative Systems & Design'; 'Macromlecular'; ...
    'Materials Science'; 'Mechanical'; ...
    'Naval Architecture and Marine'; 'Nuclear'; ...
    'Radiological Sciences'; 'Robotics'};

